use vestsiden;

LOAD DATA LOCAL INFILE '/home/bruker/vestsiden/loadfiles/file1.csv' INTO TABLE HISTORYNUMERICTRENDRECORD FIELDS TERMINATED BY ',' IGNORE 1 LINES (TIMESTAMP, VALUE, HISTORY_ID, STATUS)


