DROP DATABASE vestsiden;
CREATE DATABASE vestsiden DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
use vestsiden;


CREATE TABLE IF NOT EXISTS HISTORY_TYPE_MAP (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME varchar(500) NOT NULL UNIQUE,
	VALUEFACETS varchar(500) NOT NULL,
	PRIMARY KEY (ID)
); 

CREATE TABLE IF NOT EXISTS HISTORYNUMERICTRENDRECORD (
	ID int AUTO_INCREMENT,
	TIMESTAMP int UNSIGNED NOT NULL,
	VALUE double NOT NULL,
	STATUS smallint NOT NULL,
	HISTORY_ID smallint UNSIGNED NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (HISTORY_ID) REFERENCES HISTORY_TYPE_MAP(ID),
	INDEX (TIMESTAMP)
);
