use vestsiden;

DROP TABLE IF EXISTS HISTORYNUMERICTRENDRECORD; 

CREATE TABLE IF NOT EXISTS HISTORYNUMERICTRENDRECORD (
	HISTORY_ID smallint UNSIGNED NOT NULL,
	TIMESTAMP int UNSIGNED NOT NULL,
	VALUE float NOT NULL,
	STATUS int NOT NULL,
	PRIMARY KEY (HISTORY_ID, TIMESTAMP)
);
